version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apimockspets
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - MONGODB_URI=${MONGODB_URI}
    restart: unless-stopped
    networks:
      - apimockspets-network

networks:
  apimockspets-network:
    driver: bridge
